fix: broken links docs (#74)
* fix: precommit file

* fix:evaluation doc links

* fix: pre-commit

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -16,8 +16,18 @@ repos:
       - id: check-pruna-pro
         name: Check for pruna_pro
         entry: >
-          bash -c "git diff --cached --name-status | grep -v \"^D\" | grep -E \"^[A-Z]\\s+docs/\" | cut -f2- | while IFS= read -r file; do if [ -f \"$file\" ] && grep -q \"pruna_pro\" \"$file\"; then echo \"Error: pruna_pro found in staged file $file\"; exit 1; fi; done || [ $? -eq 1 ] && exit 1 || exit 0"
+          bash -c '
+          git diff --cached --name-status |
+          grep -v "^D" |
+          cut -f2- |                       
+          while IFS= read -r file; do
+              if [ -f "$file" ] && grep -q "pruna_pro" "$file"; then
+                  echo "Error: pruna_pro found in staged file $file"
+                  exit 1
+              fi
+          done
+          '
         language: system
         stages: [pre-commit]
-        types: [text]
-        files: '^docs/'
+        types: [python]
+        exclude: '^docs/'
